---
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["7.3", "7.4", "8.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run unit tests
        uses: php-actions/phpunit@v3.0.2
        with:
          configuration: phpunit.xml
          php_version: ${{ matrix.php }}

  lint:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run linters
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Auto commit `php-cs-fixer` changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
